name: symbolic-automata-monitors
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy~=1.21
  - scipy~=1.7
  - matplotlib~=3.4
  - spot~=2.10
  - pandoc
  - pip
  - pip:
      - z3-solver~=4.8
      - networkx~=2.6
      - pdoc
