name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - dev
      # Alternative: only build for tags.
      # tags:
      #   - '*'

permissions:
  contents: write


jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yaml
          cache-environment: true
          post-cleanup: 'all'

      - run: pip install -e .
        shell: bash -el {0}
      - run: |
          pdoc -o docs/docs/ syma '!syma.monitoring'
          pandoc --standalone -o docs/index.html --metadata title="Symbolic Automata Monitors" README.md
        shell: bash -el {0}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          keep_files: true
